[package]
name = "madparts"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rustit-be/madparts-rs"

[dependencies.gtk]
version = "0.4"
features = ["v3_10"]

[dependencies]
glib = "0.5"
gdk = "0.8"
gdk-pixbuf = "0.4"
gio = "0.4"
cairo-rs = "0.4"
inotify = "0.5"
lazy_static = "1.0"
range = "0.3"
pyo3 = "0.2"
#pyo3 = { git = "https://github.com/PyO3/pyo3.git" }
env_logger = "0.5"
log = "0.4"
clap = "2.29"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
